In [1]:
from collections import Counter
import itertools
import sys
# 添加路径
sys.path.append('/home/zentreisender/Documents/imformation/信息隐藏')
from LSB.jsteg import *
from LSB.lsbSub import *

In [2]:
# 返回卡方差总和
def chi_fang(ima):

    # 将矩阵转为数组形式
    List = list(itertools.chain.from_iterable(ima))
    arr = np.array(List)

    print(min(arr))
    print(max(arr))

    # 获得像素值对应的个数
    result = {}
    for k in range(256):
        mask = (arr == k)
        arr_new = arr[mask]
        v = arr_new.size
        result[k] = v

    # 计算相临值的卡方差
    sum = 0
    for i in range(0, 128):
        # 计算卡方差总和
        sum = pow(result[2*i]-result[2*i+1], 2)+sum

    return sum, result



In [6]:
    # 图片路径
IMAGE = r'../img/ztfn.jpg'
    # 获得灰度图片矩阵
img_arry = cv.imread(IMAGE, cv.IMREAD_GRAYSCALE)
print(img_arry)
print(img_arry.dtype.name)
    # 抽取出最低有效位平面
original_lsbMatrix = getLSBMatrix(img_arry)
print(original_lsbMatrix)
    # 均值 和方差
    #mean, variance = getMatrixDetail(original_lsbMatrix)



[[166 165 166 ... 171 171 169]
 [167 165 164 ... 169 170 174]
 [165 164 164 ... 170 170 175]
 ...
 [137 138 138 ... 218 219 220]
 [136 137 139 ... 217 218 219]
 [137 139 139 ... 217 219 221]]
uint8
[[0. 1. 0. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [4]:
embedding_lsbMatrix1, chars1 = generateWaterMark(img_arry.shape)
print(embedding_lsbMatrix1)
embedding_lsbMatrix2, chars2 = generateWaterMark(img_arry.shape)

[[0. 1. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 1. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [5]:

    #print("嵌入量：%d" %(embedding_lsbMatrix.size))
    # print("嵌入值："+chars)
encode_LSB_img1 = encodeLSB(
        embedding_lsbMatrix1,
        img_arry)
encode_LSB_img2 = encodeLSB(
        embedding_lsbMatrix2,
        img_arry)
print(encode_LSB_img1)



[[166 165 166 ... 170 171 168]
 [166 165 164 ... 168 170 175]
 [164 165 164 ... 170 170 175]
 ...
 [136 139 138 ... 218 219 221]
 [136 137 138 ... 216 219 218]
 [136 139 138 ... 216 218 220]]


In [7]:

    # print(encode_LSB_img)
chi_encode1, result1 = chi_fang(encode_LSB_img1)
chi_encode2, result2 = chi_fang(encode_LSB_img2)
chi_unencode, result = chi_fang(img_arry)

    # 打印原图像卡方差，嵌入后图像卡方差
print("chi_unencode: %d , chi_encode: %d" % (chi_unencode, chi_encode1))

0
251
1
251
1
251
chi_unencode: 3327208 , chi_encode: 26273524
